// Generated by Copilot
const { Router } = require('express')

module.exports = function createNewsRoutes(db, requireAdmin) {
  const router = Router()

  // GET all news, optionally filtered by ?sport=
  router.get('/', async (req, res) => {
    try {
      let query = `SELECT * FROM news WHERE 1=1`
      const params = []

      if (req.query.sport) {
        query += ` AND lower(sport) = ?`
        params.push(req.query.sport.toLowerCase())
      }

      query += ` ORDER BY created_at DESC`

      const rows = await db.all(query, params)
      res.json(rows)
    } catch (err) {
      console.error(err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // POST new news article
  router.post('/', requireAdmin, async (req, res) => {
    try {
      const { title, content, author, sport, image_path } = req.body

      const result = await db.run(
        `INSERT INTO news (title, content, author, sport, image_path)
         VALUES (?, ?, ?, ?, ?)`,
        [
          title,
          content,
          author || null,
          sport || 'Baseball',
          image_path || null
        ]
      )

      res.json({ success: true, id: result.lastID })
    } catch (err) {
      console.error(err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // PUT update news article
  router.put('/:id', requireAdmin, async (req, res) => {
    try {
      const { title, content, author, sport, image_path } = req.body

      const result = await db.run(
        `UPDATE news
         SET title = ?, content = ?, author = ?, sport = ?, image_path = ?
         WHERE id = ?`,
        [
          title,
          content,
          author || null,
          sport || 'Baseball',
          image_path || null,
          req.params.id
        ]
      )

      if (result.changes === 0) {
        return res.status(404).json({ error: 'not_found' })
      }

      res.json({ success: true, changes: result.changes })
    } catch (err) {
      console.error(err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // DELETE news article
  router.delete('/:id', requireAdmin, async (req, res) => {
    try {
      const result = await db.run('DELETE FROM news WHERE id = ?', req.params.id)
      if (result.changes === 0) {
        return res.status(404).json({ error: 'not_found' })
      }
      res.json({ success: true })
    } catch (err) {
      console.error(err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  return router
}
