// Generated by Copilot
const { Router } = require('express')

module.exports = function createScheduleRoutes(db, requireAdmin) {
  const router = Router()

  // GET all schedule entries, optionally filtered by ?sport=&league=&type=
  router.get('/', async (req, res) => {
    try {
      let query = `SELECT * FROM schedule WHERE 1=1`
      const params = []

      if (req.query.sport) {
        query += ` AND lower(sport) = ?`
        params.push(req.query.sport.toLowerCase())
      }
      if (req.query.league) {
        query += ` AND lower(league) = ?`
        params.push(req.query.league.toLowerCase())
      }
      if (req.query.type) {
        query += ` AND lower(type) = ?`
        params.push(req.query.type.toLowerCase())
      }

      query += ` ORDER BY date, time`

      const rows = await db.all(query, params)
      res.json(rows)
    } catch (err) {
      console.error(err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // POST new schedule entry
  router.post('/', requireAdmin, async (req, res) => {
    try {
      const {
        date,
        time,
        type,
        league,
        sport,
        location,
        opponent,
        home_away,
        notes,
        season,
        year,
        jersey_color,
        pants_color,
        hat_color
      } = req.body

      const result = await db.run(
        `
        INSERT INTO schedule (date, time, type, league, sport, location, opponent, home_away, notes, season, year, jersey_color, pants_color, hat_color)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        `,
        [
          date,
          time,
          type || 'Game',
          league,
          sport || 'Baseball',
          location || null,
          opponent || null,
          home_away || null,
          notes || null,
          season || null,
          year || null,
          jersey_color || null,
          pants_color || null,
          hat_color || null
        ]
      )

      res.json({ success: true, id: result.lastID })
    } catch (err) {
      console.error(err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // PUT update schedule entry
  router.put('/:id', requireAdmin, async (req, res) => {
    try {
      const {
        date,
        time,
        type,
        league,
        sport,
        location,
        opponent,
        home_away,
        notes,
        season,
        year,
        jersey_color,
        pants_color,
        hat_color
      } = req.body

      const result = await db.run(
        `
        UPDATE schedule
        SET date = ?, time = ?, type = ?, league = ?, sport = ?, location = ?, 
            opponent = ?, home_away = ?, notes = ?, season = ?, year = ?,
            jersey_color = ?, pants_color = ?, hat_color = ?
        WHERE id = ?
        `,
        [
          date,
          time,
          type || 'Game',
          league,
          sport || 'Baseball',
          location || null,
          opponent || null,
          home_away || null,
          notes || null,
          season || null,
          year || null,
          jersey_color || null,
          pants_color || null,
          hat_color || null,
          req.params.id
        ]
      )

      if (result.changes === 0) {
        return res.status(404).json({ error: 'not_found' })
      }

      res.json({ success: true, changes: result.changes })
    } catch (err) {
      console.error(err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // DELETE schedule entry
  router.delete('/:id', requireAdmin, async (req, res) => {
    try {
      const result = await db.run('DELETE FROM schedule WHERE id = ?', req.params.id)
      if (result.changes === 0) {
        return res.status(404).json({ error: 'not_found' })
      }
      res.json({ success: true })
    } catch (err) {
      console.error(err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  return router
}
