// Generated by Copilot
const express = require('express')
const { currentSeason } = require('../lib/migrations')
const { normalizeObject } = require('../lib/normalize')
const multer = require('multer')
const { parse } = require('csv-parse/sync')

const router = express.Router()

// Configure multer for CSV files (memory storage)
const upload = multer({
  storage: multer.memoryStorage(),
  fileFilter: (req, file, cb) => {
    if (file.mimetype === 'text/csv' || file.originalname.endsWith('.csv')) {
      cb(null, true)
    } else {
      cb(new Error('Only CSV files are allowed'))
    }
  },
  limits: { fileSize: 2 * 1024 * 1024 } // 2MB limit
})

// Stats are scoped to a season. When a request does not name one, fall back to
// the most recent season present so existing pages keep showing current numbers.
async function latestSeason(db, table, { league, sport } = {}) {
  let query = `SELECT season, year FROM ${table} WHERE year IS NOT NULL`
  const params = []

  if (sport) {
    query += ' AND lower(sport) = ?'
    params.push(String(sport).toLowerCase())
  }
  if (league) {
    query += ' AND lower(league) = ?'
    params.push(String(league).toLowerCase())
  }

  query += ' ORDER BY year DESC, id DESC LIMIT 1'
  return db.get(query, params)
}

/** The season a write belongs to: what was asked for, else the current one. */
/**
 * The newest season anywhere in the stats tables.
 *
 * Deliberately not per-table: if a new season has a team record entered but no
 * CSV uploaded yet, a per-table default would show the new season's record
 * beside the previous season's batting numbers, under one season heading.
 */
async function latestSeasonOverall(db) {
  return db.get(`
    SELECT season, year FROM (
      SELECT season, year FROM batting_stats
      UNION SELECT season, year FROM pitching_stats
      UNION SELECT season, year FROM team_stats
    )
    WHERE season IS NOT NULL AND year IS NOT NULL
    ORDER BY year DESC LIMIT 1
  `)
}

/** The season a read should return: what was asked for, else the newest on file. */
async function resolveReadSeason(db, table, query) {
  if (query.season && query.year) return { season: query.season, year: query.year }

  const latest = await latestSeasonOverall(db)
  if (!latest) return { season: query.season || null, year: query.year || null }

  return { season: query.season || latest.season, year: query.year || latest.year }
}

async function seasonForWrite(db, body) {
  if (body.season && body.year) return { season: body.season, year: body.year }

  const current = await currentSeason(db)
  return { season: body.season || current.season, year: body.year || current.year }
}

module.exports = (db, requireAdmin) => {
  // Which seasons have stats on file - drives the season picker.
  router.get('/seasons', async (req, res) => {
    try {
      const rows = await db.all(`
        SELECT DISTINCT season, year FROM (
          SELECT season, year FROM batting_stats
          UNION SELECT season, year FROM pitching_stats
          UNION SELECT season, year FROM team_stats
        )
        WHERE season IS NOT NULL AND year IS NOT NULL
        ORDER BY year DESC, season
      `)
      res.json(rows)
    } catch (err) {
      console.error('Get seasons error:', err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // Get batting stats (optionally filtered by league and sport)
  router.get('/batting', async (req, res) => {
    try {
      const { league, sport, limit } = req.query
      const { season, year } = await resolveReadSeason(db, 'batting_stats', req.query)
      let query = 'SELECT * FROM batting_stats WHERE 1=1'
      const params = []

      if (season) {
        query += ' AND season = ?'
        params.push(season)
      }
      if (year) {
        query += ' AND year = ?'
        params.push(year)
      }

      if (sport) {
        query += ' AND sport = ?'
        params.push(sport)
      }
      if (league) {
        query += ' AND league = ?'
        params.push(league)
      }

      query += ' ORDER BY avg DESC'

      if (limit) {
        query += ' LIMIT ?'
        params.push(parseInt(limit))
      }

      const stats = await db.all(query, params)
      res.json(stats)
    } catch (err) {
      console.error('Get batting stats error:', err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // Get pitching stats (optionally filtered by league and sport)
  router.get('/pitching', async (req, res) => {
    try {
      const { league, sport, limit } = req.query
      const { season, year } = await resolveReadSeason(db, 'pitching_stats', req.query)
      let query = 'SELECT * FROM pitching_stats WHERE 1=1'
      const params = []

      if (season) {
        query += ' AND season = ?'
        params.push(season)
      }
      if (year) {
        query += ' AND year = ?'
        params.push(year)
      }

      if (sport) {
        query += ' AND sport = ?'
        params.push(sport)
      }
      if (league) {
        query += ' AND league = ?'
        params.push(league)
      }

      query += ' ORDER BY era ASC'

      if (limit) {
        query += ' LIMIT ?'
        params.push(parseInt(limit))
      }

      const stats = await db.all(query, params)
      res.json(stats)
    } catch (err) {
      console.error('Get pitching stats error:', err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // Get team stats (optionally filtered by league and sport)
  router.get('/team', async (req, res) => {
    try {
      const { league, sport } = req.query
      const { season, year } = await resolveReadSeason(db, 'team_stats', req.query)
      let query = 'SELECT * FROM team_stats WHERE 1=1'
      const params = []

      if (season) {
        query += ' AND season = ?'
        params.push(season)
      }
      if (year) {
        query += ' AND year = ?'
        params.push(year)
      }

      // Compared case-insensitively: the team page lowercases the age group
      // from the URL ('10u') while the stored value is '10U'.
      if (sport) {
        query += ' AND lower(sport) = ?'
        params.push(String(sport).toLowerCase())
      }
      if (league) {
        query += ' AND lower(league) = ?'
        params.push(String(league).toLowerCase())
      }

      query += ' ORDER BY wins DESC, losses ASC'

      const stats = await db.all(query, params)
      res.json(stats)
    } catch (err) {
      console.error('Get team stats error:', err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // Update a team's win/loss/tie record by hand. The stats CSV has no team
  // record in it, so this is the only way those numbers get set.
  router.put('/team/record', requireAdmin, async (req, res) => {
    try {
      const { league, team_name, wins, losses, ties } = req.body
      const sport = req.body.sport || 'Baseball'

      if (!league) {
        return res.status(400).json({ error: 'League is required' })
      }

      const toCount = (value) => {
        const parsed = parseInt(value)
        return isNaN(parsed) || parsed < 0 ? 0 : parsed
      }

      const record = {
        wins: toCount(wins),
        losses: toCount(losses),
        ties: toCount(ties)
      }

      const { season, year } = await seasonForWrite(db, req.body)

      const existing = await db.get(
        `SELECT id, team_name FROM team_stats
          WHERE lower(league) = ? AND lower(sport) = ? AND season = ? AND year = ?
          ORDER BY id LIMIT 1`,
        [String(league).toLowerCase(), String(sport).toLowerCase(), season, year]
      )

      if (existing) {
        // Leave runs_scored / runs_allowed alone — those come from the CSV
        await db.run(
          `UPDATE team_stats
           SET team_name = ?, wins = ?, losses = ?, ties = ?, updated_at = datetime('now')
           WHERE id = ?`,
          [team_name || existing.team_name, record.wins, record.losses, record.ties, existing.id]
        )
      } else {
        await db.run(
          `INSERT INTO team_stats
           (league, sport, team_name, wins, losses, ties, runs_scored, runs_allowed, season, year)
           VALUES (?, ?, ?, ?, ?, ?, 0, 0, ?, ?)`,
          [league, sport, team_name || league, record.wins, record.losses, record.ties, season, year]
        )
      }

      res.json({ success: true, ...record })
    } catch (err) {
      console.error('Update team record error:', err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // Upload comprehensive team stats CSV (batting + pitching + team stats all in one file)
  router.post('/upload', requireAdmin, upload.single('file'), async (req, res) => {
    try {
      if (!req.file) {
        return res.status(400).json({ error: 'No file uploaded' })
      }

      // Multer parses this body after the global normaliser has run, so these
      // fields are normalised here instead.
      normalizeObject(req.body)

      const { league, sport } = req.body
      if (!league) {
        return res.status(400).json({ error: 'League is required' })
      }

      const { season, year } = await seasonForWrite(db, req.body)

      // Extract team name from filename (e.g., "KC Kryptonite 9U Spring 2026 Stats.csv")
      const filename = req.file.originalname
      let teamName = 'Unknown Team'
      
      // Try to extract team name from filename pattern: "Team Name XU Season Year Stats.csv"
      const match = filename.match(/^(.+?)\s+\d+U/i)
      if (match) {
        teamName = match[1].trim()
      }

      // Parse CSV - handle multi-row headers
      const allRecords = parse(req.file.buffer, {
        columns: false, // Get raw arrays
        skip_empty_lines: true,
        trim: true,
        relax_column_count: true
      })

      if (allRecords.length < 3) {
        return res.status(400).json({ error: 'Invalid CSV format: not enough rows' })
      }

      // Known column indices for this CSV format (GameChanger stats export)
      const BATTING_COLS = {
        LAST: 1,
        FIRST: 2,
        AB: 5,
        AVG: 6,
        H: 10,
        DOUBLES: 12,
        TRIPLES: 13,
        HR: 14,
        RBI: 15,
        RUNS: 16,
        SB: 25
      }

      const PITCHING_COLS = {
        IP: 54,
        W: 59,
        L: 60,
        SV: 61,
        H_ALLOWED: 65,
        RUNS_ALLOWED: 66,
        BB: 68,
        SO: 69,
        ERA: 72
      }

      // The CSV carries no team record, so hold on to any hand-entered W/L/T
      // and put it back after the rebuild instead of resetting it to 0-0
      const priorRecords = await db.all(
        'SELECT team_name, wins, losses, ties FROM team_stats WHERE league = ? AND sport = ?',
        [league, sport || 'Baseball']
      )
      const priorByTeam = new Map(priorRecords.map(r => [r.team_name, r]))

      // Delete existing stats for this league/sport
      // A GameChanger export is the full picture for its season, so replacing
      // is correct - but only within that season. Without the season and year
      // here, uploading a new season would delete the previous one.
      for (const table of ['batting_stats', 'pitching_stats', 'team_stats']) {
        await db.run(
          `DELETE FROM ${table}
            WHERE lower(league) = ? AND lower(sport) = ? AND season = ? AND year = ?`,
          [String(league).toLowerCase(), String(sport || 'Baseball').toLowerCase(), season, year]
        )
      }

      let battingCount = 0
      let pitchingCount = 0
      const teamStatsMap = new Map()

      // Process data rows (starting from row 3, index 2)
      for (let i = 2; i < allRecords.length; i++) {
        const row = allRecords[i]
        
        // Stop at empty rows, totals, or glossary
        if (!row[0] || !row[BATTING_COLS.FIRST] || 
            row[0].toLowerCase().includes('glossary') || 
            row[0].toLowerCase().includes('totals')) {
          break
        }

        // Build player name from First + Last
        const firstName = row[BATTING_COLS.FIRST] || ''
        const lastName = row[BATTING_COLS.LAST] || ''
        const playerName = `${firstName} ${lastName}`.trim()
        
        if (!playerName) continue

        // Insert batting stats (if has valid AVG and AB)
        const avgStr = row[BATTING_COLS.AVG]
        const abStr = row[BATTING_COLS.AB]
        
        if (avgStr && abStr) {
          const avgValue = parseFloat(avgStr)
          const abValue = parseInt(abStr)
          
          if (!isNaN(avgValue) && !isNaN(abValue) && abValue > 0) {
            await db.run(
              `INSERT INTO batting_stats 
               (league, sport, player_name, team, avg, hits, at_bats, runs, rbis, doubles, triples, home_runs, stolen_bases, season, year)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
              [
                league,
                sport || 'Baseball',
                playerName,
                teamName,
                avgValue,
                parseInt(row[BATTING_COLS.H]) || null,
                abValue,
                parseInt(row[BATTING_COLS.RUNS]) || null,
                parseInt(row[BATTING_COLS.RBI]) || null,
                parseInt(row[BATTING_COLS.DOUBLES]) || null,
                parseInt(row[BATTING_COLS.TRIPLES]) || null,
                parseInt(row[BATTING_COLS.HR]) || null,
                parseInt(row[BATTING_COLS.SB]) || null,
                season,
                year
              ]
            )
            battingCount++
            
            // Accumulate runs for team stats
            const runs = parseInt(row[BATTING_COLS.RUNS]) || 0
            if (runs > 0) {
              if (!teamStatsMap.has(teamName)) {
                teamStatsMap.set(teamName, {
                  runs_scored: 0,
                  runs_allowed: 0,
                  wins: 0,
                  losses: 0,
                  ties: 0
                })
              }
              teamStatsMap.get(teamName).runs_scored += runs
            }
          }
        }

        // Insert pitching stats (if has valid ERA and IP)
        const eraStr = row[PITCHING_COLS.ERA]
        const ipStr = row[PITCHING_COLS.IP]
        
        if (eraStr && ipStr) {
          const eraValue = parseFloat(eraStr)
          const ipValue = parseFloat(ipStr)
          
          if (!isNaN(eraValue) && !isNaN(ipValue) && ipValue > 0) {
            await db.run(
              `INSERT INTO pitching_stats 
               (league, sport, player_name, team, era, wins, losses, saves, innings_pitched, strikeouts, walks, hits_allowed, season, year)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
              [
                league,
                sport || 'Baseball',
                playerName,
                teamName,
                eraValue,
                parseInt(row[PITCHING_COLS.W]) || null,
                parseInt(row[PITCHING_COLS.L]) || null,
                parseInt(row[PITCHING_COLS.SV]) || null,
                ipValue,
                parseInt(row[PITCHING_COLS.SO]) || null,
                parseInt(row[PITCHING_COLS.BB]) || null,
                parseInt(row[PITCHING_COLS.H_ALLOWED]) || null,
                season,
                year
              ]
            )
            pitchingCount++
            
            // Accumulate runs allowed for team stats
            const runsAllowed = parseInt(row[PITCHING_COLS.RUNS_ALLOWED]) || 0
            if (runsAllowed > 0) {
              if (!teamStatsMap.has(teamName)) {
                teamStatsMap.set(teamName, {
                  runs_scored: 0,
                  runs_allowed: 0,
                  wins: 0,
                  losses: 0,
                  ties: 0
                })
              }
              teamStatsMap.get(teamName).runs_allowed += runsAllowed
            }
          }
        }
      }

      // Insert team stats (one team per file)
      let teamCount = 0
      for (const [teamName, stats] of teamStatsMap) {
        // Fall back to the league's only prior row so a renamed CSV file
        // doesn't silently drop the record
        const prior = priorByTeam.get(teamName) || priorRecords[0]

        await db.run(
          `INSERT INTO team_stats
           (league, sport, team_name, wins, losses, ties, runs_scored, runs_allowed, season, year)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
          [
            league,
            sport || 'Baseball',
            teamName,
            prior?.wins || stats.wins || 0,
            prior?.losses || stats.losses || 0,
            prior?.ties || stats.ties || 0,
            stats.runs_scored || 0,
            stats.runs_allowed || 0,
            season,
            year
          ]
        )
        teamCount++
      }

      res.json({ 
        success: true, 
        batting: battingCount,
        pitching: pitchingCount,
        teams: teamCount
      })
    } catch (err) {
      console.error('Upload stats error:', err)
      res.status(500).json({ error: err.message })
    }
  })

  return router
}
