// Generated by Copilot
const { Router } = require('express')
const { normalizeLeague } = require('../lib/normalize')

const PLAYER_COLUMNS = `
  id,
  player_number,
  first_name,
  last_name,
  favorite_food,
  favorite_movie,
  bio,
  photo_path,
  league,
  season,
  year,
  sport
`

module.exports = function createTeamRoutes(db, requireAdmin) {
  const router = Router()

  // GET all teams, optionally filtered by ?sport=Baseball
  router.get('/', async (req, res) => {
    try {
      const sport = req.query.sport

      let query = `
        SELECT DISTINCT league, sport
        FROM coaches
        WHERE archive = 'N'
      `
      const params = []

      if (sport) {
        query += ` AND lower(sport) = ?`
        params.push(sport.toLowerCase())
      }

      query += ` ORDER BY league`

      const rows = await db.all(query, params)
      res.json(rows)

    } catch (err) {
      console.error(err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // GET available sports
  router.get('/sports', async (req, res) => {
    try {
      const rows = await db.all(`
        SELECT DISTINCT sport
        FROM coaches
        WHERE archive = 'N'
        ORDER BY sport
      `)
      res.json(rows.map(r => r.sport))
    } catch (err) {
      console.error(err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // Archive or restore a team.
  //
  // There is no team table to delete a row from, and no foreign keys tying the
  // players, stats and schedule to one, so a real delete would silently strand
  // all of it. Archiving is what the club already does at the end of a season:
  // the coaches keep the season on file, and every listing hides them.
  router.put('/:league/archive', requireAdmin, async (req, res) => {
    try {
      const league = normalizeLeague(req.params.league) || ''
      const { sport, season, year, archived } = req.body

      if (!sport || !season || year === undefined || year === null) {
        return res.status(400).json({ error: 'sport_season_year_required' })
      }

      // Scoped to one season rather than the whole league: a league carries a
      // row per season, and restoring must not drag every past one back with it.
      const result = await db.run(
        `
        UPDATE coaches
        SET archive = ?
        WHERE lower(league) = lower(?)
          AND lower(sport)  = lower(?)
          AND lower(season) = lower(?)
          AND year          = ?
        `,
        [archived === false ? 'N' : 'Y', league, sport, season, year]
      )

      if (!result.changes) return res.status(404).json({ error: 'team_not_found' })

      res.json({ success: true, changes: result.changes })
    } catch (err) {
      console.error(err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // Copy a squad into a new season.
  //
  // Most of a roster comes back year on year, and re-entering eleven players
  // by hand at every rollover is where the time goes. The photo path is carried
  // across deliberately: the cleanup counts references before removing a file,
  // so two seasons pointing at one photo is safe.
  router.post('/:league/roster-copy', requireAdmin, async (req, res) => {
    try {
      const league = normalizeLeague(req.params.league) || ''
      const { sport, fromSeason, fromYear, toSeason, toYear } = req.body

      if (!sport || !fromSeason || !toSeason || fromYear == null || toYear == null) {
        return res.status(400).json({ error: 'sport_and_both_seasons_required' })
      }

      // Refuse rather than double up: running this twice would give the season
      // two of every player, which is tedious to unpick by hand.
      const existing = await db.get(
        `SELECT COUNT(*) AS n FROM players
          WHERE lower(league) = lower(?) AND lower(sport) = lower(?)
            AND lower(season) = lower(?) AND year = ?`,
        [league, sport, toSeason, toYear]
      )
      if (existing.n) return res.status(409).json({ error: 'season_already_has_players' })

      const result = await db.run(
        `
        INSERT INTO players (
          player_number, first_name, last_name, favorite_food, favorite_movie,
          bio, photo_path, league, season, year, sport
        )
        SELECT
          player_number, first_name, last_name, favorite_food, favorite_movie,
          bio, photo_path, league, ?, ?, sport
        FROM players
        WHERE lower(league) = lower(?)
          AND lower(sport)  = lower(?)
          AND lower(season) = lower(?)
          AND year          = ?
        `,
        [toSeason, toYear, league, sport, fromSeason, fromYear]
      )

      res.json({ success: true, copied: result.changes })
    } catch (err) {
      console.error(err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  // GET team details
  router.get('/:league', async (req, res) => {
    try {
      // Path params never pass through the body/query normaliser, so a hand-typed
      // or stale URL is cleaned up here.
      const league = (normalizeLeague(req.params.league) || '').toLowerCase()

      // Ordered rather than an arbitrary LIMIT 1: if a league is ever left with
      // two live seasons, the newest is the one the site should be showing.
      const coach = await db.get(`
        SELECT
          first_name,
          last_name,
          league,
          season,
          year
        FROM coaches
        WHERE lower(league) = ?
          AND archive = 'N'
        ORDER BY year DESC,
          CASE lower(season)
            WHEN 'fall' THEN 3
            WHEN 'summer' THEN 2
            WHEN 'spring' THEN 1
            ELSE 0
          END DESC
        LIMIT 1
      `, league)

      // Assistants hang off the head coach's composite key, so there is nobody
      // to look up until we know which coach is current for this league.
      // Compared case-insensitively, as league names vary in casing ('10u'/'10U').
      const assistants = coach
        ? await db.all(`
            SELECT first_name, last_name
            FROM assistants
            WHERE lower(head_coach_last_name) = lower(?)
              AND lower(head_coach_league)    = lower(?)
              AND lower(head_coach_season)    = lower(?)
              AND head_coach_year             = ?
            ORDER BY last_name, first_name
          `, [coach.last_name, coach.league, coach.season, coach.year])
        : []

      // Scoped to the coach's season. Without it a league accumulates every
      // roster it has ever had, so last autumn's players sit alongside this
      // spring's on the same page. No live season means nothing to show.
      const players = coach
        ? await db.all(`
            SELECT
              ${PLAYER_COLUMNS}
            FROM players
            WHERE lower(league)  = ?
              AND lower(season)  = lower(?)
              AND year           = ?
            ORDER BY player_number
          `, [league, coach.season, coach.year])
        : []

      res.json({
        league: coach?.league ?? req.params.league,
        headCoach: coach
          ? `${coach.first_name} ${coach.last_name}`
          : null,
        assistantCoaches: assistants.map((a) => `${a.first_name} ${a.last_name}`),
        players
      })

    } catch (err) {
      console.error(err)
      res.status(500).json({ error: 'internal_error' })
    }
  })

  return router
}
