// Generated by Copilot
import api from './client'

export async function checkAdmin(): Promise<boolean> {
  try {
    const { data } = await api.get('/admin/check')
    return data.authenticated === true
  } catch {
    return false
  }
}
