// Generated by Copilot
import api from './client'

export interface CurrentUser {
  id: number | null
  username: string
  email: string | null
  role: 'admin' | 'editor'
}

/** Ask the server who we are. Returns null when the session is absent or stale. */
export async function fetchCurrentUser(): Promise<CurrentUser | null> {
  try {
    const { data } = await api.get<{ authenticated: boolean; user: CurrentUser }>('/auth/me')
    return data.authenticated ? data.user : null
  } catch {
    return null
  }
}

export async function login(username: string, password: string): Promise<CurrentUser> {
  const { data } = await api.post<{ user: CurrentUser }>('/auth/login', { username, password })
  return data.user
}

export async function logout(): Promise<void> {
  try {
    await api.post('/auth/logout')
  } catch {
    // Already logged out server-side is not an error worth surfacing.
  }
}
