// Generated by Copilot
import axios from 'axios'
import api from './client'

export interface CurrentUser {
  id: number | null
  username: string
  email: string | null
  role: 'admin' | 'editor'
}

/** Ask the server who we are. Returns null when the session is absent or stale. */
export async function fetchCurrentUser(): Promise<CurrentUser | null> {
  try {
    const { data } = await api.get<{ authenticated: boolean; user: CurrentUser }>('/auth/me')
    return data.authenticated ? data.user : null
  } catch {
    return null
  }
}

export async function login(username: string, password: string): Promise<CurrentUser> {
  const { data } = await api.post<{ user: CurrentUser }>('/auth/login', { username, password })
  return data.user
}

export async function logout(): Promise<void> {
  try {
    await api.post('/auth/logout')
  } catch {
    // Already logged out server-side is not an error worth surfacing.
  }
}

export interface PasswordChangeResult {
  ok: boolean
  error?: string
}

/** Change your own password. Requires the current one, so a borrowed session can't do it. */
export async function changePassword(
  currentPassword: string,
  newPassword: string
): Promise<PasswordChangeResult> {
  try {
    await api.post('/auth/password', {
      current_password: currentPassword,
      new_password: newPassword,
    })
    return { ok: true }
  } catch (err) {
    if (axios.isAxiosError(err)) {
      const status = err.response?.status
      const code = err.response?.data?.error

      if (status === 401) return { ok: false, error: 'Your current password is not correct.' }
      if (code === 'password_too_short') {
        const min = err.response?.data?.minimum ?? 12
        return { ok: false, error: `Your new password must be at least ${min} characters.` }
      }
      if (code === 'not_a_database_user') {
        return { ok: false, error: 'This login cannot change its own password.' }
      }
      if (!err.response) return { ok: false, error: 'Cannot reach the server. Check your connection.' }
    }

    return { ok: false, error: 'Something went wrong. Please try again.' }
  }
}
