// Generated by Copilot
import api from './client'

export interface Assistant {
  id?: number
  head_coach_last_name: string
  head_coach_league: string
  head_coach_season: string
  head_coach_year: number
  first_name: string
  last_name: string
}

export async function getAssistants(): Promise<Assistant[]> {
  const { data } = await api.get('/assistants')
  return data
}

export async function createAssistant(assistant: Omit<Assistant, 'id'>): Promise<{ success: boolean; id: number }> {
  const { data } = await api.post('/assistants', assistant)
  return data
}

export async function updateAssistant(id: number, assistant: Omit<Assistant, 'id'>): Promise<{ success: boolean; changes: number }> {
  const { data } = await api.put(`/assistants/${id}`, assistant)
  return data
}

export async function deleteAssistant(id: number): Promise<{ success: boolean }> {
  const { data } = await api.delete(`/assistants/${id}`)
  return data
}
