// Generated by Copilot
import axios from 'axios'

const api = axios.create({
  baseURL: '/api',
})

// Inject Basic Auth header when credentials exist in sessionStorage
api.interceptors.request.use((config) => {
  const credentials = sessionStorage.getItem('admin_credentials')
  if (credentials) {
    config.headers.Authorization = `Basic ${credentials}`
  }
  return config
})

export default api
