// Generated by Copilot
import axios from 'axios'

const api = axios.create({
  baseURL: '/api',
  // Session lives in an httpOnly cookie, so it must ride along with every
  // request. It is not readable from JavaScript by design.
  withCredentials: true,
})

export default api
