// Generated by Copilot
import api from './client'

export interface Coach {
  first_name: string
  last_name: string
  league: string
  season: string
  year: number
  archive: string
  sport?: string
}

export async function getCoaches(): Promise<Coach[]> {
  const { data } = await api.get('/coaches')
  return data
}

export async function createCoach(coach: Coach): Promise<{ success: boolean }> {
  const { data } = await api.post('/coaches', coach)
  return data
}

export async function updateCoach(
  lastName: string,
  league: string,
  season: string,
  year: number,
  coach: Coach
): Promise<{ success: boolean; changes: number }> {
  const { data } = await api.put(`/coaches/${lastName}/${league}/${season}/${year}`, coach)
  return data
}

export async function deleteCoach(
  lastName: string,
  league: string,
  season: string,
  year: number
): Promise<{ success: boolean }> {
  const { data } = await api.delete(`/coaches/${lastName}/${league}/${season}/${year}`)
  return data
}
