// Generated by Copilot
import api from './client'

export interface NewsArticle {
  id: number
  title: string
  content: string
  author: string | null
  sport: string
  created_at: string
  image_path: string | null
}

export type NewNewsArticle = Omit<NewsArticle, 'id' | 'created_at'>

export async function getNews(sport?: string): Promise<NewsArticle[]> {
  const params = sport ? { sport } : {}
  const { data } = await api.get('/news', { params })
  return data
}

export async function createNews(article: NewNewsArticle): Promise<{ success: boolean; id: number }> {
  const { data } = await api.post('/news', article)
  return data
}

export async function updateNews(id: number, article: NewNewsArticle): Promise<{ success: boolean; changes: number }> {
  const { data } = await api.put(`/news/${id}`, article)
  return data
}

export async function deleteNews(id: number): Promise<{ success: boolean }> {
  const { data } = await api.delete(`/news/${id}`)
  return data
}
