// Generated by Copilot
import api from './client'

export interface Player {
  id: number
  player_number: number
  first_name: string
  last_name: string
  favorite_food: string
  favorite_movie: string
  bio: string
  photo_path: string
  league: string
  season: string
  year: number
  sport: string
}

export async function getPlayers(): Promise<Player[]> {
  const { data } = await api.get('/players')
  return data
}

export async function getPlayer(number: number, league?: string): Promise<Player> {
  const { data } = await api.get(`/players/${number}`, {
    params: league ? { league } : {},
  })
  return data
}

export async function createPlayer(player: Omit<Player, 'id'>): Promise<{ success: boolean; id: number }> {
  const { data } = await api.post('/players', player)
  return data
}

export async function updatePlayer(id: number, player: Omit<Player, 'id'>): Promise<{ success: boolean; changes: number }> {
  const { data } = await api.put(`/players/${id}`, player)
  return data
}

export async function deletePlayer(id: number): Promise<{ success: boolean }> {
  const { data } = await api.delete(`/players/${id}`)
  return data
}
