// Generated by Copilot
import api from './client'

export interface ScheduleEntry {
  id: number
  date: string
  time: string
  type: 'Game' | 'Practice'
  league: string
  sport: string
  location: string | null
  opponent: string | null
  home_away: 'Home' | 'Away' | null
  notes: string | null
  season: string | null
  year: number | null
  jersey_color: string | null
  pants_color: string | null
  hat_color: string | null
}

export type NewScheduleEntry = Omit<ScheduleEntry, 'id'>

export async function getSchedule(filters?: { sport?: string; league?: string; type?: string }): Promise<ScheduleEntry[]> {
  const { data } = await api.get('/schedule', { params: filters })
  return data
}

export async function createScheduleEntry(entry: NewScheduleEntry): Promise<{ success: boolean; id: number }> {
  const { data } = await api.post('/schedule', entry)
  return data
}

export async function updateScheduleEntry(id: number, entry: NewScheduleEntry): Promise<{ success: boolean; changes: number }> {
  const { data } = await api.put(`/schedule/${id}`, entry)
  return data
}

export async function deleteScheduleEntry(id: number): Promise<{ success: boolean }> {
  const { data } = await api.delete(`/schedule/${id}`)
  return data
}
