// Generated by Copilot
import api from './client'

export interface BattingStat {
  id: number
  league: string
  sport: string
  player_name: string
  team: string | null
  avg: number | null
  hits: number | null
  at_bats: number | null
  runs: number | null
  rbis: number | null
  doubles: number | null
  triples: number | null
  home_runs: number | null
  stolen_bases: number | null
  updated_at: string
}

export interface PitchingStat {
  id: number
  league: string
  sport: string
  player_name: string
  team: string | null
  era: number | null
  wins: number | null
  losses: number | null
  saves: number | null
  innings_pitched: number | null
  strikeouts: number | null
  walks: number | null
  hits_allowed: number | null
  updated_at: string
}

export interface TeamStat {
  id: number
  league: string
  sport: string
  team_name: string
  wins: number | null
  losses: number | null
  ties: number | null
  runs_scored: number | null
  runs_allowed: number | null
  updated_at: string
}

export interface Season {
  season: string
  year: number
}

/** Seasons that have stats on file, newest first. */
export async function getSeasons(): Promise<Season[]> {
  const { data } = await api.get('/stats/seasons')
  return data
}

export async function getBattingStats(params?: { league?: string; sport?: string; limit?: number; season?: string; year?: number }): Promise<BattingStat[]> {
  const { data } = await api.get('/stats/batting', { params })
  return data
}

export async function getPitchingStats(params?: { league?: string; sport?: string; limit?: number; season?: string; year?: number }): Promise<PitchingStat[]> {
  const { data } = await api.get('/stats/pitching', { params })
  return data
}

export async function getTeamStats(params?: { league?: string; sport?: string; season?: string; year?: number }): Promise<TeamStat[]> {
  const { data } = await api.get('/stats/team', { params })
  return data
}

export interface TeamRecord {
  league: string
  sport: string
  team_name?: string
  season?: string
  year?: number
  wins: number
  losses: number
  ties: number
}

export async function updateTeamRecord(record: TeamRecord): Promise<{ success: boolean; wins: number; losses: number; ties: number }> {
  const { data } = await api.put('/stats/team/record', record)
  return data
}

export async function uploadTeamStats(
  file: File,
  league: string,
  sport: string,
  season: string,
  year: number
): Promise<{ success: boolean; batting: number; pitching: number; teams: number }> {
  const formData = new FormData()
  formData.append('file', file)
  formData.append('league', league)
  formData.append('sport', sport)
  formData.append('season', season)
  formData.append('year', String(year))

  const { data } = await api.post('/stats/upload', formData, {
    headers: {
      'Content-Type': 'multipart/form-data'
    }
  })
  
  return data
}
