// Generated by Copilot
import api from './client'

export interface SwagItem {
  id: number
  title: string
  description: string | null
  price: number
  image_path: string | null
  sport: string
  url: string | null
  created_at: string
}

export type NewSwagItem = Omit<SwagItem, 'id' | 'created_at'>

export async function getSwag(sport?: string): Promise<SwagItem[]> {
  const params = sport ? { sport } : {}
  const { data } = await api.get('/swag', { params })
  return data
}

export async function createSwag(item: NewSwagItem): Promise<{ success: boolean; id: number }> {
  const { data } = await api.post('/swag', item)
  return data
}

export async function updateSwag(id: number, item: NewSwagItem): Promise<{ success: boolean; changes: number }> {
  const { data } = await api.put(`/swag/${id}`, item)
  return data
}

export async function deleteSwag(id: number): Promise<{ success: boolean }> {
  const { data } = await api.delete(`/swag/${id}`)
  return data
}
