// Generated by Copilot
import api from './client'
import type { Player } from './players'

export interface Team {
  league: string
  sport: string
}

export interface TeamDetail {
  league: string
  headCoach: string | null
  assistantCoaches: string[]
  players: Player[]
}

export async function getTeams(sport?: string): Promise<Team[]> {
  const params = sport ? { sport } : {}
  const { data } = await api.get('/teams', { params })
  return data
}

export async function getSports(): Promise<string[]> {
  const { data } = await api.get('/teams/sports')
  return data
}

export async function getTeam(league: string): Promise<TeamDetail> {
  const { data } = await api.get(`/teams/${league}`)
  return data
}
