// Generated by Copilot
import api from './client'

export interface UploadResponse {
  success: boolean
  path: string
  filename: string
  size: number
}

export async function uploadImage(file: File): Promise<UploadResponse> {
  const formData = new FormData()
  formData.append('image', file)

  const { data } = await api.post<UploadResponse>('/upload/image', formData, {
    headers: {
      'Content-Type': 'multipart/form-data'
    }
  })
  
  return data
}
