// Generated by Copilot
const crypto = require('crypto')

/**
 * Basic Auth middleware for admin routes.
 * Expects credentials in ADMIN_USER and ADMIN_PASS environment variables.
 * Clients send: Authorization: Basic <base64(user:pass)>
 */
function requireAdmin(req, res, next) {
  const adminUser = process.env.ADMIN_USER
  const adminPass = process.env.ADMIN_PASS

  if (!adminUser || !adminPass) {
    console.error('ADMIN_USER and ADMIN_PASS environment variables must be set')
    return res.status(500).json({ error: 'server_misconfigured' })
  }

  const authHeader = req.headers.authorization
  if (!authHeader || !authHeader.startsWith('Basic ')) {
    res.set('WWW-Authenticate', 'Basic realm="Admin"')
    return res.status(401).json({ error: 'authentication_required' })
  }

  const encoded = authHeader.slice(6)
  let decoded
  try {
    decoded = Buffer.from(encoded, 'base64').toString('utf8')
  } catch {
    return res.status(401).json({ error: 'invalid_credentials' })
  }

  const separatorIndex = decoded.indexOf(':')
  if (separatorIndex === -1) {
    return res.status(401).json({ error: 'invalid_credentials' })
  }

  const user = decoded.slice(0, separatorIndex)
  const pass = decoded.slice(separatorIndex + 1)

  // Timing-safe comparison to prevent timing attacks
  const userMatch = timingSafeCompare(user, adminUser)
  const passMatch = timingSafeCompare(pass, adminPass)

  if (!userMatch || !passMatch) {
    return res.status(401).json({ error: 'invalid_credentials' })
  }

  next()
}

function timingSafeCompare(input, expected) {
  const inputBuf = Buffer.from(input, 'utf8')
  const expectedBuf = Buffer.from(expected, 'utf8')

  if (inputBuf.length !== expectedBuf.length) {
    // Compare against expected anyway to avoid timing leak on length
    crypto.timingSafeEqual(expectedBuf, expectedBuf)
    return false
  }

  return crypto.timingSafeEqual(inputBuf, expectedBuf)
}

module.exports = requireAdmin
