<!-- Generated by Copilot -->
<template>
  <div class="min-h-screen flex items-center justify-center p-8">
    <div class="w-full max-w-sm">
      <h1 class="text-2xl font-black text-ibc-navy text-center mb-6">Admin Login</h1>

      <form @submit.prevent="handleLogin" class="space-y-4">
        <div>
          <label class="block text-sm font-semibold mb-1">Username</label>
          <input
            v-model="username"
            type="text"
            class="w-full p-2 border rounded"
            required
            autocomplete="username"
          />
        </div>

        <div>
          <label class="block text-sm font-semibold mb-1">Password</label>
          <input
            v-model="password"
            type="password"
            class="w-full p-2 border rounded"
            required
            autocomplete="current-password"
          />
        </div>

        <div v-if="error" class="text-red-600 text-sm bg-red-50 p-2 rounded">
          {{ error }}
        </div>

        <button
          type="submit"
          :disabled="loading"
          class="w-full py-2 bg-ibc-navy text-white font-bold rounded hover:bg-ibc-blue transition disabled:opacity-50"
        >
          {{ loading ? 'Logging in...' : 'Log In' }}
        </button>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'

const router = useRouter()
const auth = useAuthStore()

const username = ref('')
const password = ref('')
const error = ref('')
const loading = ref(false)

async function handleLogin() {
  error.value = ''
  loading.value = true

  const success = await auth.login(username.value, password.value)

  loading.value = false

  if (success) {
    router.push('/admin/players')
  } else {
    error.value = 'Invalid username or password'
  }
}
</script>
