// Generated by Copilot
import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
import axios from 'axios'
import { fetchCurrentUser, login as loginRequest, logout as logoutRequest } from '@/api/admin'
import type { CurrentUser } from '@/api/admin'

export interface LoginResult {
  ok: boolean
  error?: string
}

export const useAuthStore = defineStore('auth', () => {
  const user = ref<CurrentUser | null>(null)

  // The session cookie is httpOnly, so the browser cannot read it. Whether we
  // are logged in is only knowable by asking the server - which we do once per
  // page load and then remember.
  const loaded = ref(false)
  let inFlight: Promise<void> | null = null

  const isAuthenticated = computed(() => user.value !== null)
  const isAdmin = computed(() => user.value?.role === 'admin')

  async function ensureLoaded(): Promise<void> {
    if (loaded.value) return

    // Concurrent navigations must not each fire their own request.
    if (!inFlight) {
      inFlight = fetchCurrentUser()
        .then((current) => {
          user.value = current
          loaded.value = true
        })
        .finally(() => {
          inFlight = null
        })
    }

    return inFlight
  }

  async function login(username: string, password: string): Promise<LoginResult> {
    try {
      user.value = await loginRequest(username, password)
      loaded.value = true
      return { ok: true }
    } catch (err) {
      user.value = null

      if (axios.isAxiosError(err)) {
        if (err.response?.status === 429) {
          const wait = Number(err.response.data?.retry_after) || 0
          const minutes = Math.ceil(wait / 60)
          return {
            ok: false,
            error: `Too many failed attempts. Try again in ${minutes} minute${minutes === 1 ? '' : 's'}.`,
          }
        }
        if (err.response?.status === 401) {
          return { ok: false, error: 'Invalid username or password' }
        }
        if (!err.response) {
          return { ok: false, error: 'Cannot reach the server. Check your connection.' }
        }
      }

      return { ok: false, error: 'Something went wrong. Please try again.' }
    }
  }

  async function logout(): Promise<void> {
    await logoutRequest()
    user.value = null
    loaded.value = true
  }

  /** Called by the axios interceptor when the server rejects our session. */
  function clear(): void {
    user.value = null
    loaded.value = true
  }

  return { user, isAuthenticated, isAdmin, loaded, ensureLoaded, login, logout, clear }
})
