// Generated by Copilot
import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
import { checkAdmin } from '@/api/admin'

export const useAuthStore = defineStore('auth', () => {
  const credentials = ref<string | null>(
    sessionStorage.getItem('admin_credentials')
  )

  const isAuthenticated = computed(() => !!credentials.value)

  function getAuthHeader(): Record<string, string> {
    if (!credentials.value) return {}
    return { Authorization: `Basic ${credentials.value}` }
  }

  async function login(username: string, password: string): Promise<boolean> {
    const encoded = btoa(`${username}:${password}`)
    // Temporarily store so the axios interceptor picks it up
    sessionStorage.setItem('admin_credentials', encoded)

    const success = await checkAdmin()

    if (success) {
      credentials.value = encoded
      return true
    }

    sessionStorage.removeItem('admin_credentials')
    return false
  }

  function logout() {
    credentials.value = null
    sessionStorage.removeItem('admin_credentials')
  }

  return { isAuthenticated, getAuthHeader, login, logout }
})
