// Generated by Copilot
import { defineStore } from 'pinia'
import { ref } from 'vue'
import { getPlayers, getPlayer, createPlayer, updatePlayer, deletePlayer, type Player } from '@/api/players'

export const usePlayerStore = defineStore('players', () => {
  const players = ref<Player[]>([])
  const loading = ref(false)

  async function fetchAll() {
    loading.value = true
    try {
      players.value = await getPlayers()
    } finally {
      loading.value = false
    }
  }

  /**
   * Jersey numbers repeat across teams, so a number alone does not identify a
   * player. Pass the league when you know it; without one this can only return
   * whichever player happens to be found first.
   */
  async function fetchOne(number: number, league?: string): Promise<Player | undefined> {
    const matches = (p: Player) =>
      p.player_number === number &&
      (!league || (p.league || '').toLowerCase() === league.toLowerCase())

    const cached = players.value.find(matches)
    if (cached) return cached

    try {
      return await getPlayer(number, league)
    } catch {
      return undefined
    }
  }

  async function add(player: Omit<Player, 'id'>) {
    const result = await createPlayer(player)
    await fetchAll()
    return result
  }

  async function update(id: number, player: Omit<Player, 'id'>) {
    const result = await updatePlayer(id, player)
    await fetchAll()
    return result
  }

  async function remove(id: number) {
    const result = await deletePlayer(id)
    await fetchAll()
    return result
  }

  return { players, loading, fetchAll, fetchOne, add, update, remove }
})
