// Generated by Copilot
import { defineStore } from 'pinia'
import { ref } from 'vue'
import { getPlayers, getPlayer, createPlayer, updatePlayer, deletePlayer, type Player } from '@/api/players'

export const usePlayerStore = defineStore('players', () => {
  const players = ref<Player[]>([])
  const loading = ref(false)

  async function fetchAll() {
    loading.value = true
    try {
      players.value = await getPlayers()
    } finally {
      loading.value = false
    }
  }

  async function fetchOne(number: number): Promise<Player | undefined> {
    // Return from cache if available
    const cached = players.value.find(p => p.player_number === number)
    if (cached) return cached

    try {
      const player = await getPlayer(number)
      return player
    } catch {
      return undefined
    }
  }

  async function add(player: Omit<Player, 'id'>) {
    const result = await createPlayer(player)
    await fetchAll()
    return result
  }

  async function update(id: number, player: Omit<Player, 'id'>) {
    const result = await updatePlayer(id, player)
    await fetchAll()
    return result
  }

  async function remove(playerNumber: number) {
    const result = await deletePlayer(playerNumber)
    await fetchAll()
    return result
  }

  return { players, loading, fetchAll, fetchOne, add, update, remove }
})
