// Generated by Copilot
import { defineStore } from 'pinia'
import { ref } from 'vue'
import { getSports } from '@/api/teams'

export const useSportStore = defineStore('sport', () => {
  const activeSport = ref<string>(
    sessionStorage.getItem('active_sport') || 'Baseball'
  )
  const availableSports = ref<string[]>(['Baseball'])

  function setSport(sport: string) {
    activeSport.value = sport
    sessionStorage.setItem('active_sport', sport)
  }

  async function fetchSports() {
    try {
      const sports = await getSports()
      if (sports.length) {
        availableSports.value = sports
      }
    } catch {
      // keep defaults
    }
  }

  return { activeSport, availableSports, setSport, fetchSports }
})
